### ISSUE TITLE
ทำ Sound

### ISSUE THREAD

**Issue by zepdon** [Natsathon/Basic-com-group-12#17]
เสียงประกอบโครงงาน รอบที่1

1.คลิกที่ตัวน้องตอนนอน https://www.epidemicsound.com/track/wKoRBTXkKu/
2.เก็บเลือด https://www.epidemicsound.com/track/DGdHs4L1KK/
3 เลือดลด https://www.epidemicsound.com/track/R2T6dNJqvc/
4 เก็บโล่ https://www.epidemicsound.com/track/9T1glOfOT5/
5 โล่แตก https://www.epidemicsound.com/track/IjrqHWBRuo/
6 เก็บSlow https://www.epidemicsound.com/track/uxK4Wps2MO/
7 เก็บลดขนาด https://www.epidemicsound.com/track/zcqGjDDsit/
8 ขยายตัวเท่าเดิม https://www.epidemicsound.com/track/oLVuzh5XUk/
9 ปุ่ม Retry https://www.epidemicsound.com/track/1IjCY2WrU7/
10 เก็บตัว A https://www.epidemicsound.com/track/TAQeTDnyGU/
11 แจ้งเตือนก่อนยิง https://www.epidemicsound.com/track/8iYsRJoWJ5/
12 ซาวเกม https://www.epidemicsound.com/track/3otoDafqbl/
13 เล่นเกมแพ้ https://www.epidemicsound.com/track/FoeV7YN1O6/
14.แตะพื้นหลัง https://www.epidemicsound.com/track/WZGknzGyeS/
15.ปีศาจ https://www.epidemicsound.com/track/6S0MnQrkPu/

**Comment by JaoJEs** [comment]
เอฟเฟคปุ่ม
สะกด เดินย่อง ๆ https://www.epidemicsound.com/track/wKoRBTXkKu/ 

สิ้นหวัง https://www.epidemicsound.com/track/v07FQLEcsS/ 

ช้า1 https://www.epidemicsound.com/track/uxK4Wps2MO/ 
ช้า2 https://www.epidemicsound.com/track/4EjseuvsOr/  
ช้า3 https://www.epidemicsound.com/track/L0uhxZFlXp/ 

หัวใจ https://www.epidemicsound.com/track/DGdHs4L1KK/ 

เสียงปล่อยมิดไซ https://www.epidemicsound.com/track/PZLk36LgWr/ 1
https://www.epidemicsound.com/track/EkdiHzK61V/ 2

เสียงการเคลื่อนที่ของมิดไซ https://www.epidemicsound.com/track/EkdiHzK61V/ 
ยิง แบบสั้น ห้วนๆ https://www.epidemicsound.com/track/BeDBQx51fJ/  
สั้น ๆ ห้วน ๆ https://www.epidemicsound.com/track/KMC4Oln8gG/ 
ยาวมานิดนึง ห้วน ๆ https://www.epidemicsound.com/track/Zqf9RbH0o0/ 
ห้วน ๆ https://www.epidemicsound.com/track/U4auZ98jgw/ 

ตอบสนองต่อไอเทม https://www.epidemicsound.com/track/TAQeTDnyGU/

แตะสิ่งของ1 https://www.epidemicsound.com/track/DdSwLW4CBW/
แตะสิ่งของ2 https://www.epidemicsound.com/track/IjrqHWBRuo/ 
แตะสิ่งของ3 https://www.epidemicsound.com/track/2p5N7JUTRz/  
แตะสิ่งของ4 https://www.epidemicsound.com/track/9T1glOfOT5/  
แตะสิ่งของ5 https://www.epidemicsound.com/track/zcqGjDDsit/

เสียงให้พร1 https://artlist.io/sfx/track/christmas-spirit---magical-harp-memory-mystery/52626 

เสียงให้พรแบบงง ๆ 2 https://artlist.io/sfx/track/christmas-spirit---magical-harp-old-memory/52627 

เอฟเฟค เสียงความฝัน ความนึกคิด https://artlist.io/sfx/track/classic-recalls---dreamy-marimba/75478

เอฟเฟคแนว แฟนตาซี https://artlist.io/sfx/track/magical-themes---fantasy-flashback-logo-/120762

ขัดจังหวะ https://www.epidemicsound.com/track/PByTxwVNlB/ 

เล่นแพ้ https://www.epidemicsound.com/track/FoeV7YN1O6/

**Comment by JaoJEs** [comment]
เสียงประกอบโครงงาน รอบที่1

1.คลิกที่ตัวน้องตอนนอน  https://www.epidemicsound.com/track/wKoRBTXkKu/ 
2.เก็บเลือด https://www.epidemicsound.com/track/DGdHs4L1KK/ 
3 เลือดลด https://www.epidemicsound.com/track/R2T6dNJqvc/ 
4 เก็บโล่ https://www.epidemicsound.com/track/9T1glOfOT5/ 
5 โล่แตก https://www.epidemicsound.com/track/IjrqHWBRuo/ 
6 เก็บSlow https://www.epidemicsound.com/track/uxK4Wps2MO/ 
7 เก็บลดขนาด https://www.epidemicsound.com/track/zcqGjDDsit/ 
8 ขยายตัวเท่าเดิม https://www.epidemicsound.com/track/oLVuzh5XUk/ 
9 ปุ่ม Retry https://www.epidemicsound.com/track/1IjCY2WrU7/ 
10 เก็บตัว A https://www.epidemicsound.com/track/TAQeTDnyGU/
11 แจ้งเตือนก่อนยิง https://www.epidemicsound.com/track/8iYsRJoWJ5/ 
12 ซาวเกม  https://www.epidemicsound.com/track/3otoDafqbl/
13 เล่นเกมแพ้ https://www.epidemicsound.com/track/FoeV7YN1O6/
14.แตะพื้นหลัง https://www.epidemicsound.com/track/WZGknzGyeS/ 
15.ปีศาจ https://www.epidemicsound.com/track/6S0MnQrkPu/
