### ISSUE TITLE
Homing(?) Dangers

### ISSUE THREAD

**Issue by zepdon** [Natsathon/Basic-com-group-12#28]

**Comment by JaoJEs** [comment]
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141816483/530ec0e6-62e2-41e0-81fd-b82bbeda9969)
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141816483/1b0b9913-c14a-410c-b7a5-4af4daaf3d55)
