### ISSUE TITLE
ทำเก็บScore/Top score

### ISSUE THREAD

**Issue by zepdon** [Natsathon/Basic-com-group-12#35]

**Comment by zepdon** [comment]
ทำเลขแล้ว
 เหลือบันทึกค่าTop score

**Comment by JaoJEs** [comment]
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141816483/ec86b40d-ce59-42c0-b5a5-1ec0f6964c6e)
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141816483/96f94a85-e0c9-438f-9013-f0794e84127f)
