### ISSUE TITLE
การทำงานของ Designer

### ISSUE THREAD

**Issue by JaoJEs** [Natsathon/Basic-com-group-12#50]
งานที่ได้รับมอบหมายจากการประชุมครั้งที่ 1 วันที่ 6/9/66

วาดบอสทั้ง 2 เฟส
เปลี่ยนพื้นหลังเพิ่มความตื่นตัวให้ผู้เล่น
เพิ่มแถบแจ้งเตือนบอส
ปุ่มtutorialและtutorial

**Comment by Korn-Sriwattana** [comment]
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/ee8ca3ef-f04d-4338-b815-d5dfeefc78d4)![Uploading 265924405...]

**Comment by Korn-Sriwattana** [comment]
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/c7619bb0-7ac6-43bc-bac5-74d778e011ba)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/802a0234-81ac-4be6-ade0-d4bad415fa43)![Uploading 265924590...]![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/182c9130-ed11-4827-96c3-a6b202daa539)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/9f0c2aa7-edf2-4a12-be39-3b42abbeffa8)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/13bf5b86-9281-4727-a0f0-d51e230019c9)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/27f7caa8-edbc-4428-9fe9-9f78d2497d25)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/eda5bbc4-ecf0-416f-bb60-5a04f58df069)

**Comment by Korn-Sriwattana** [comment]
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/fc4b6428-1329-4c02-820b-0f18cdce552b)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/6f262921-43e5-4666-88fe-9620f4120704)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/1d113763-dba2-49d5-ae54-a71ef64fde9e)

**Comment by Korn-Sriwattana** [comment]
ความคืบหน้าวันที่7/9/23
รูป1,2: ฉากหลังตอนบอสมาคร่าวๆ(มีไฟ/แสงสีแดง)
รูป3: warning
รูป4: ตัวอย่างถ้าใช้ฉากหลังเวลามีบอสมากับwarning
รูป5: tutorial
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/b779e2b8-0d2a-4b5f-b02e-26e1c0170681)
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/95a153fc-6e32-4244-9054-92e757bc40bd)
![Uploading 266360009...]![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/02cc61f9-0900-4489-ba4b-3b7f4baf108a)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/90516072-0d2e-4ee9-98cb-b9351add1727)![image](https://github.com/Natsathon/Basic-com-group-12/assets/141802927/2e579fb3-08a6-4ab5-b606-0b0fd8a91c31)
