### ISSUE TITLE
ติดตามการทำงาน Tester

### ISSUE THREAD

**Issue by JaoJEs** [Natsathon/Basic-com-group-12#52]
ความคืบหน้าหลังจากการประชุม

ครั้งที่ 1 วันที่ 6/9/66 

ลองเล่นเพื่อหาฟีดแบ็ค
หาสไปร์ทที่บอสยิงออกมานอกจากลูกไฟ และอุปสรรค์

**Comment by Natsathon** [comment]
1.เปลี่ยนฉาก | ให้ตรง Score เป็นตัวกำหนดการเปลี่ยนฉาก
2.ง่าย ไป ยาก ไป ยากมาก อาจจะเป็นบอส
3.ความสมูทของฉากหลัง เวลาที่เคลื่อนที่ไหลลื่น ต่อเนื่องกัน
4.ฉากหลังอาจจะงาน Art เช่น สถานที่ใน มช
5.ปรับขนาดองค์ประกอบให้เหมาะกับเวที
6.เพิ่มความน่าสนใจตอนบอสโผล่ อาจจะมีการแจ้งเตือนก่อนปล่อยบอส เปลี่ยนสีพื้นหลังเป็นสีดำ สีแดง
7.มีสิ่งกีดขวางที่ไม่ทำให้เลือดลด แต่ทำให้ผู้เล่นติด เดินไปต่อไม่ได้
8..พื้นหลังควรซีด เพื่อเพิ่มพื้นที่เล่น

**Comment by Natsathon** [comment]
1.เปลี่ยนสีพื้นหลัง
2.แถบแสดงแจ้งเตือน การมีถึงของบอส
3.tutorail

**Comment by Natsathon** [comment]
1.เพิ่มฉากเปลี่ยนสถานที่(ห้อง) เพื่อที่ผู้เล่นจะได้รู้สึกว่าแมพมีระยะทางที่มากขึ้น
2.เพิ่มมินิบอสเล็กๆเพื่อให้รู้สึกว่ามีเส้นทางต้องฝ่าฟันก่อนเจอลาสบอส มินิบอสอาจเป็นรายวิชาต่างๆเช่นอุปกรณ์ดรออิ้ง,FBD/รูปประกอบฟิสิกส์ ฯลฯ
3.ตอนชนเห็ดอยากให้ปรับขนานให้ใหญ่ขึ้นนิดนึง มองว่าตอนชนเห็ดตัวละครเล็กเกินไปทำให้เก็บ A ได้ยาก

**Comment by Natsathon** [comment]
1.ปรับตัวเลขเวลาเกิดของต่างๆ Ex.Power ups Boss Spawn time
2.Boss HP BAR
3.ปรับความเหมาะสมความเร็ว
4.เพิ่มหน้าต่าง how to play
5.เพิ่มปุ่มวิธีการเล่น
6.เวลาเกิดของบอสให้ชัดเจน

**Comment by Natsathon** [comment]
1.เพิ่มแถบเตือน ให้รู้ว่าบอสกำลังจะเกิด
