### ISSUE TITLE
Warning & Red BG b4 boss spawn

### ISSUE THREAD

**Issue by zepdon** [Natsathon/Basic-com-group-12#63]
done

**Comment by JaoJEs** [comment]
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141816483/a76b39e0-e4bd-4401-9196-30cc662b585b)
![image](https://github.com/Natsathon/Basic-com-group-12/assets/141816483/518d52d3-f500-4eb6-9f3f-eb5e768b78a0)
